using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Storage.Models
{

    /// <summary>
    /// Each role has a list of users. 
    /// Entity ramework does not support storing of dictionaries. A phase can have  (key) delegated tu multiple users (value).
    /// This class is used to store each key/value pair from a dictionary as a record in the table with a foreign key to the principal entity (Phase, previously contained dictionary).
    /// </summary>
    public class PhaseRole
    {
        #region Referenced entities 

        public virtual ICollection<StoredUser> Users { get; set; } // Value in dictionary 

        #endregion

        #region Keys 

        public int Id { get; set; } // unique autogenerated database key

        // public int StoredRoleId { get; set; }
        public virtual StoredRole Role { get; set; } // Key in dictionary and FK to Role entity 

        //public int StoredPhaseId { get; set; } // FK to principal Phase entity 
        public virtual StoredPhase Phase { get; set; }

        #endregion
    }

}
