using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Storage.Models
{
    /// <summary>
    /// Each requested datafield has a list of conflicts in a task. 
    /// Entity ramework does not support storing of dictionaries. A phase can have  (key) delegated tu multiple users (value).
    /// This class is used to store each key/value pair from a dictionary as a record in the table with a foreign key to the principal entity (TaskRequest, previously contained 2D array).
    /// </summary>
    public class TaskConflicts
    {

        #region Referenced entities 

        public virtual ICollection<StoredConflict> Conflicts { get; set; } // Values 

        #endregion

        #region Keys 

        [Key]
        public int Id { get; set; } // unique autogenerated database key

        //public int DataFieldId { get; set; }

        public virtual StoredDataField DataField { get; set; } // Key 

        //public int TaskId { get; set; } // FK to principal entity

        public virtual StoredTaskRequest Task { get; set; }

        #endregion

    }

}
